# Try_Except

**_try_** block let's test a block of code for errors.
**_except_** block let's handle the error.
**_else_** block lets execute code is no error.
**_finally_** block lets execute after try and except.

**_Program : try except_**

```python
# let's do something error

try :
    this is error;
except :
    print(">>>> error is here. <<<<");
finally :
    print(">>> it run whatever what <<<");

try :
    print("\n\n>>> No error <<<");
except :
    print(">>> It can not run because no error here <<<");
else :
    print(">>> it run because try block code is correct <<<");
finally :
    print(">>> it run whatever what <<<");
```

**_Output : try except_**

```
>>>> error is here. <<<<
>>> it run whatever what <<<


>>> No error <<<
>>> it run because try block code is correct <<<
>>> it run whatever what <<<
```

<hr />
<br />

[< Built in Modules](19.built_in_modules.md) | [README >](./../README.md)
---